#:kivy 2.1.0

<LabelWidget>:
    # Color:
    #     rgba: 0, 1, 0, 1
    size: 100,10
    Label:
        font_size: 70  
        text: "hello"
        halign: 'center'
        valign: 'middle'
        markup: True
        size: self.size
        center_x: 500
        y: 50
        
<TestWidget>:
    test_label: testlabel

    LabelWidget:
        id: testlabel
        #center: self.parent.center
        #top: root.top - 50
